services:
  postgres:
    image: postgres:15-alpine
    container_name: exchange_postgres
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: exchange_redis
    ports:
      - "6379:6379"